baseURL = "https://jedraynes.com"
languageCode = "en"
defaultContentLanguage = "en"
title = "Jed Raynes"
theme = "LoveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
# googleAnalytics = ""
disqusShortname = "jedraynes"

[author]
  name = "Jed Raynes"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[Permalinks]
 about = "/:year/:filename/"
 posts = "/:year/:filename/"
 contact = "/:year/:filename/"

[params]
  version = "0.2.X"
  #custom_css = "/css/_custom.css"
[params.home]
  rss = 10
  [params.home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = "jedr125@gmail.com"
    #title = "Jed Raynes"
    subtitle = "Hi, I'm Jed"
    typeit = true
    social = true
    disclaimer = ""
    # Home page posts
  [params.home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 3
    # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
    # default behavior when you don't set "hiddenFromHomePage" in front matter
    defaultHiddenFromHomePage = false

[params.gravatar]
  email = "jedr125@gmail.com"
[params.header]
  desktopMode = "auto"
  mobileMode = "auto"
[params.footer]
  since = 2020
  icp = ""
  license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
[params.page]
  lightgallery = true
  linkToMarkdown = true

  google_verification = ""
  bing_verification = ""
  yandex_verification = ""
  pinterest_verification = ""
  baidu_verification = ""

[params.cdn]                                       #### CSS and JS Files CDN
  fontawesome_free_css = ''                           # for example '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.10.1/css/all.min.css" integrity="sha256-fdcFNFiBMrNfWL6OcAGQz6jDgNTRxnrLEd4vJYFWScE=" crossorigin="anonymous">'
  animate_css = ''
  gitalk_css = ''
  gitalk_js = ''
  valine_js = ''
  jquery_js = ''
  lazysizes_js = ''
  smooth_scroll_js = ''
  katex_css = ''
  katex_js = ''
  katex_auto_render_js = ''
  mermaid_js = ''
  echarts_js = ''
  echarts_macarons_js = ''
  typeit_js = ''
  jquery_countdown_js = ''
  aplayer_css = ''
  aplayer_js = ''
  meting_js = ''

  [params.social]                                        # Social Info in home page
    GitHub = "jedraynes"
    Linkedin = "jedraynes"
    #Twitter = "xxxx"
    #Instagram = "xxxx"
    #Email = "xxxx"
    #Facebook = "xxxx"
    #Telegram = "xxxx"
    #Medium = "xxxx"
    #Gitlab = "xxxx"
    #Youtubelegacy = "xxxx"
    #Youtubecustom = "xxxx"
    #Youtubechannel = "xxxx"
    #Tumblr ="xxxx"
    #Quora = "xxxx"
    #Keybase = "xxxx"
    #Pinterest = "xxxx"
    #Reddit = "xxxx"
    #Codepen = "xxxx"
    #Bitbucket = "xxxx"
    #Stackoverflow = "xxxx"
    #Weibo = "xxxx"
    #Odnoklassniki = "xxxx"
    #VKontakte = "xxxx"
    #Flickr = "xxxx"
    #Xing = "xxxx"
    #Snapchat = "xxxx"
    #Soundcloud = "xxxx"
    #Spotify = "xxxx"
    #Bandcamp = "xxxx"
    #Paypal = "xxxx"
    #Fivehundredpx = "xxxx"
    #Mix = "xxxx"
    #Goodreads = "xxxx"
    #Lastfm = "xxxx"
    #Foursquare = "xxxx"
    #Hackernews = "xxxx"
    #Kickstarter = "xxxx"
    #Patreon = "xxxx"
    #Steam = "xxxx"
    #Twitch = "xxxx"
    #Strava = "xxxx"
    #Skype = "xxxx"
    #Whatsapp = "xxxx"
    #Zhihu = "xxxx"
    #Douban = "xxxx"
    #Angellist = "xxxx"
    #Slidershare = "xxxx"
    #Jsfiddle = "xxxx"
    #Deviantart = "xxxx"
    #Behance = "xxxx"
    #Dribble = "xxxx"
    #Wordpress = "xxxx"
    #Vine = "xxxx"
    #Googlescholar = "xxxx"
    #Researchgate = "xxxx"
    #Mastodon = "xxxx"
    #Thingiverse = "xxxx"

  [params.share]                                         # Social Share Links in post page
    enable = true
    Twitter = true
    Facebook = true
    Reddit = true
    #Linkedin = true
    #Pinterest = true
    #HackerNews = true
    #Mix = true
    #Tumblr = true
    #VKontakte = true
    #Weibo = true

  [params.publisher]                                     # Publisher Info just for SEO
    name = "XXXX"
    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  [params.logo]                                          # Website Log Info just for SEO
    url = "logo.png"
    width = 127
    height = 40

  [params.image]                                         # Website Image Info just for SEO
    url = "cover.png"
    width = 800
    height = 600

  [params.gitalk]                                        # Gittalk Comment Config (https://github.com/gitalk/gitalk)
    owner = ""
    repo = ""
    clientId = ""
    clientSecret = ""

  [params.valine]                                        # Valine Comment Config (https://github.com/xCss/Valine)
    enable = false
    appId = ""
    appKey = ""
    notify = false
    verify = true
    avatar = ""
    placeholder = "Your comment ..."
    visitor = true
    recordIP = true

[menu]
  [[menu.main]]
    identifier = "about"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "About"
    url = "/about"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "contact"
    pre = ""
    post = ""
    name = "Contact"
    url = "/contact"
    title = ""
    weight = 3
  #[[menu.main]]
    #identifier = "tags"
    #pre = ""
    #post = ""
    #name = "Tags"
    #url = "/tags"
    #title = ""
    #weight = 4
  #[[menu.main]]
    #identifier = "categories"
    #pre = ""
    #post = ""
    #name = "Categories"
    #url = "/categories"
    #title = ""
    #weight = 5

[privacy]                                             #### Privacy Info (https://gohugo.io/about/hugo-and-gdpr/)
  [privacy.googleAnalytics]
    anonymizeIP = true

  [privacy.youtube]
    privacyEnhanced = true

[mediaTypes]                                          #### Options to make hugo output .md files.
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]                              #### Options to make hugo output .md files.
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]                                             #### Options to make hugo output .md files.
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]